name: Unit Testing

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Make Clean
      run: make clean
    - name: Make All
      run: make all
    - name: Run Executable
      run: ./test
    - name: Clean Up Files
      run: make clean
